### ISSUE TITLE
Manual installation issues with rbac crd-reader

### ISSUE THREAD

**Issue by noelo** [petbattle/pet-battle-infra#5]
helm upgrade --install pet-battle-infra petbattle/pet-battle-infra --version=1.0.24 --set install_cert_util=true 
Release "pet-battle-infra" does not exist. Installing it now.
Error: failed post-install: warning: Hook post-install pet-battle-infra/templates/crd-reader.yaml failed: clusterroles.rbac.authorization.k8s.io "crd-reader" already exists

**Comment by eformat** [comment]
fixed by https://github.com/petbattle/pet-battle-infra/commit/29b7ddaf1cc604fcb17898157548ce4c1a8a4594
